# https://tailscale.com/blog/docker-tailscale-guide
services:
  ts-pbridge:
    image: tailscale/tailscale:latest
    hostname: peanutbutter
    environment:
      # this is required and must match the secret
      - TS_EXTRA_ARGS=--advertise-tags=tag:personal
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SERVE_CONF=/config/ts_serve.json
    env_file: "ts.env"
    volumes:
      - ./ts-data:/var/lib/tailscale:Z
      - ./config/ts_serve.json:/config/ts_serve.json:ro
    devices:
      - /dev/net/tun:/dev/net/tun:Z
    cap_add:
      - net_admin
      - net_raw
      - sys_module
    restart: unless-stopped
  pbridge:
    build: ./protonmail-bridge-docker/build
    network_mode: service:ts-pbridge
    depends_on: 
      - ts-pbridge
volumes:
  ts-pbridge-data:
    driver: local
  tailscale-data-pbridge:
    driver: local
